### ISSUE TITLE
[HW] Hitesh Reddy Peram

### ISSUE THREAD

**Issue by hitesh13** [DataStax-Academy/Intro-to-Cassandra-for-Developers#102] opened 2021-05-13 17:06 UTC
**Name:** Hitesh Reddy Peram
**Email:** hitesh13071999@gmail.com
<img width="1792" alt="Screenshot 2021-05-13 at 9 59 51 PM" src="https://user-images.githubusercontent.com/31627925/118160197-a341ca00-b43b-11eb-89e4-c6f62e281b9e.png">
<img width="1792" alt="Screenshot 2021-05-13 at 9 52 31 PM" src="https://user-images.githubusercontent.com/31627925/118160209-a8067e00-b43b-11eb-8431-1d4d8b000dca.png">

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

<SCREENSHOT>

**Comment by SonicDMG** [comment] 2021-05-13 20:55
This is a duplicate of https://github.com/DataStax-Academy/Intro-to-Cassandra-for-Developers/issues/101 where we also have our conversation. I'll close this one out and use the other for your homework badge.

**Closed by SonicDMG** 2021-05-13 20:55 UTC
Labels: homework, wait for review
